name: Rubocop

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run Rubocop
        run: |
          bundle config set --local deployment 'false'
          bundle install --jobs 4 --retry 3
          bundle exec rubocop -f github
